[package]
name = "rustty"
version = "0.1.9"
authors = ["Cole Reynolds <cpjreynolds@gmail.com>"]
description = "A terminal UI library"
documentation = "https://cpjreynolds.github.io/rustty"
repository = "https://github.com/cpjreynolds/rustty"
homepage = "https://github.com/cpjreynolds/rustty"
readme = "README.md"
license = "MIT"
keywords = ["terminal", "ui", "tui", "console", "tty"]

[dependencies]
nix = "0.4"
term = "0.5"
lazy_static = "0.1"
libc = "0.1"
gag = "0.1.6"
